record(nome('ACHILLEA MILLEFOLIUM'),
nomescomum('Milef�lio, Erva-carpinteira, Macela-de-S�o-Jo�o'),
sinonimo('None'),
familia('Aster�ceas (Asteraceae)'),
origem('Europa'),
historia('O milef�lio j� era utilizado na antiguidade para tratamento de ferimentos de guerra, podendo, por isso, tamb�m chamar-se herba militaris (Erva-dos-soldados)'),
floracao('De junho a Outubro.'),
caracteristica('Trata-se de uma planta arom�tica, com uma altura que pode chegar aos 60 cm e com caules erectos e lanosos. As folhas alternas e duplamente penatipartidas t�m um tom verde acizentado.A infloresc�ncia � formada por  uma pan�cula em forma de umbela, apre sentando flores do disco amarelas (no interior) e flores liguladas brancas ou rosa (no exterior).'),
habitat('O milef�lio cresce em solos ricos em azoto, � beira de caminhos, em prados, campos secos e terrenos baldios. Cultivado em jardins, n�o � muito exigente e apenas necessita de sol.'),
propriedades('o milef�lio possui qualidades calmantes e anti-espasm�dicas. A achilelna contida na planta tem um efeito cicatrizante. Os rebentos colhem-se a partir de Maio. A planta em flor colhe-se entre junho e Setembro. A secagem faz-se com as plantas atadas em molhos e penduradas num local arejado e � sombra.'),
cozinha('Rebentos e folhas frescas e picadas podem ser utilizados em saladas.'),
saude('Em casos de c�licas e problemas relacionados com a digest�o, a planta em flor pode ser empregada como t�nico. Ajuda a tens�o arterial a descer, contribui para uma melhor circula��o sangu�nea, produzindo tamb�m um efeito ben�fico no caso de varizes e de rinite al�rgica, bem como durante o per�odo menstrual. As flores deitadas em �gua quente libertam vapores que revitalizam a pele do rosto.')).

record(nome('AGASTACHE FOENICULUM'),
nomescomum('Hissopo-anisado'),
sinonimo('Agastache anethiodora'),
familia('Lami�ceas (Larniaceae).'),
origem('Am�rica do Norte.'),
historia('Esta planta j� era conhecida pelos ind�genas norte americanos devido aos seus valores nutritivo e medicinal. Foi introduzida na Europa por apicultores, pois as suas flores constituem uma excelente fonte de alimento para as abelhas.'),
floracao('De junho a Setembro.'),
caracteristica('Planta vivaz, resistente no Inverno, cujo caule pode atingir 90 cm de altura. Possui grandes infloresc�ncias de cor p�rpura e folhas verde-prateadas, com comprimento at� 8 cm, sabor adocicado e cheiro a anis.'),
habitat('Esta planta cresce bem em vasos ou no jardim, em s�tios expostos ao sol ou em locais semi-sombrios, com solo perme�vel. Na Europa Central n�o necessita de ser protegida da geada.'),
propriedades('Destacam-se os efeitos anti-inflamat�rios e digestivos. As folhas devem ser colhidas antes de a planta florir, e podem ser utilizadas frescas ou secas.'),
cozinha('As folhas frescas podem ser utiliza das na prepara��o de saladas e na produ��o de licores; as flores s�o um excelente elemento decorativo em saladas e sobremesas.'),
saude('A partir das folhas secas pode-se fazer um ch� que alivia dores de garganta, constipa��es e que acalma o est�mago. As flores, frescas ou secas, servem de decora��o em arranjos florais.')).

record(nome('ALCEA ROSEA'),
nomescomum('Malva�sco, Flor-de-pau'),
sinonimo('None'),
familia('Malv�ceas (Malvaceae).'),
origem('Pa�ses Mediterr�nicos.'),
historia('None'),
floracao('De Julho a Setembro.'),
caracteristica(' No primeiro ano, o malva�sco desenvolve apenas uma roseta basilar. Na Primavera seguinte, formam-se os caules hirsutos, com uma altura at� 2,5 m. As folhas, palmatilobadas e tomentosas, apresentam uma base foliar cordiforme e margens dentadas. A cor das flores, que podem atingir 10 cm de largura, varia entre o vermelho, o rosa, o branco, o amarelo e o p�rpura-escuro.'),
habitat('Na terra de origem, a planta cresce em terrenos baldios, rochosos e junto �s linhas f�rreas. No jardim, por�m, o mal va�sco necessita de um lugar com sol ou com meia-sombra, protegido do vento, e de um solo com nutrientes em abund�ncia.'),
propriedades('o malva�sco tem propriedades expectorantes e diur�ticas. Utilizam-se as ra�zes, as folhas e sobretudo as flores. Estas s�o recolhidas pouco antes de desabrocharem, sendo que as flores escuras s�o prefer�veis �s brancas e amarelas. Podem ser utilizadas frescas ou secas. Neste �ltimo caso, devem ser guardadas num local escuro.'),
cozinha('Os corantes contidos nas flores podem ser aproveitados para colorir licores e alimentos.'),
saude('As flores do malva�sco fazem frequentemente parte dos ingredientes das infus�es para a tosse e para a bronquite. As infus�es podem ser utilizadas para gargarejar, aliviando inflama��es da mucosa da boca e da garganta.')).

record(nome('ALCHEMILLA XANTHOCHLORA'),
nomescomum('P�-de-le�o, Mata-boi, Patal�-dos-vales'),
sinonimo('Alquemila vulgaris.'),
familia('None'),
origem('Europa.'),
historia('A designa��o popular em alem�o e em ingl�s � �capa de Senhora� � prov�m da forma das folhas, que, supostamente, faz lembrar a capa de Nossa Senhora, raz�o pela qual na Idade M�dia a planta era sugerida para resolver toda a esp�cie de �problemas das mulheres�.'),
floracao('De Maio a Setembro.'),
caracteristica('Trata-se de uma planta perene, que pode crescer at� 40 cm de altura, com uma roseta basilar de folhas pubescentes e palmatilobadas e com flores grandes, verdes e discretas, dispostas em pan�culas arredondadas.'),
habitat('Cresce preferencialmente em campos e prados, mas tamb�m pode ser encontrada perto de florestas e em margens de rios, tratando-se de uma planta com grande dissemina��o. Cultivada em jardins, n�o requer muitos cuidados.'),
propriedades('o p�-de-le�o possui qualidades adstringentes e anti-inflamat�rias, sendo tamb�m ligeiramente anti-s�ptico. As folhas devem ser colhidas entre Maio e Julho, e secas � sombra, devendo-se vir�-las com frequ�ncia.'),
cozinha('As folhas novas podem ser utilizadas em saladas.'),
saude('Como j� foi mencionado, o p�-de-le�o � empregado como rem�dioeficaz nos �problemas das mulheres, aliviando inclusivamente dores menstruais muito fortes. Gra�as ao seu efeito adstringente, estanca a perda de sangue e acelera o processo de cicatriza��o. O efeito adstringente tamb�m � �til em casos de diarreia e de catarro intestinal.')).

record(nome('ALLIARIA PETIOLATA'),
nomescomum('Erva-alheira, Ali�ria'),
sinonimo('Alliaria officinalis.'),
familia('Brassic�ceas (Brassicaceae).'),
origem('Europa e �sia.'),
historia('None'),
floracao('De Abril a Maio.'),
caracteristica('Trata-se de uma planta que pode atingir 1 metro de altura, apresentando flores brancas e pequenas. As folhas basilares possuem pec�olos longos e s�o reniformes e crenadas, enquanto as folhas caulinares s�o cordiformes ou delt�ides, podendo ser s�sseis ou possuir um pec�olo curto.'),
habitat('Abunda na Europa Central, principalmente em clareiras, orlas de bosques, arbustos e  terrenos baldios. Em jardins, requer um lugar com meia-sombra e com solo perme�vel.'),
propriedades('a erva-alheira possui propriedades expectorantes, actua ligeiramente como anti-s�ptico e estimula a respira��o. Todas as partes da planta podem ser utilizadas. Deve ser colhida entre Maio e Julho e preparada no momento, pois n�o � pr�pria para ser guardada.'),
cozinha('Trata-se de uma planta que se adequa �s mais variadas receitas. As tenras folhas proporcionam, devido ao seu ligeiro paladar a alho, um sabor especial em saladas, em queijo quark, em manteiga de ervas e em quiches. Picada, serve de conduto para o p�o. A raiz pode ser preparada como o r�bano-silvestre e as vagens podem servir para substituir a mostarda.'),
saude('Enquanto erva medicinal, desempenha um papel ben�fico, sobre tudo na �rea das vias respirat�rias. Antigamente era utilizada, dado o seu efeito anti-s�ptico, como elixir contra inflama��es das gengivas.')).

record(nome('ALLIUM CEPA'),
nomescomum('Cebola'),
sinonimo('None'),
familia('Ali�ceas (Alliaceae).'),
origem('�sia Ocidental.'),
historia('No M�dio Oriente e na China, j� se cultiva cebola h� mais de mil anos. Chegou � Europa Central provavelmente com os romanos. Na Idade M�dia, pendurava-se cebolas por cima da porta para repelir a Peste Negra.'),
floracao('De Junho a Agosto.'),
caracteristica('Trata-se de uma planta perene, com uma altura at� 90 cm, com caules e folhas ocas e infloresc�ncias grandes e arredondadas, cuja cor varia entre o branco e o p�rpura. Existem numerosas variedades de cebolas, o que muitas vezes se evidencia na cor da casca exterior, podendo esta apresentar tons brancos, amarelados, castanhos-claros ou avermelhados.'),
habitat('A cebola � cultivada um pouco por todo o mundo. Necessita de sol e de um solo pouco pesado.'),
propriedades('a cebola pode orgulhar-se da sua longa lista de efeitos medicinais. E considerada diur�tica, actua como anti-inflamat�rio, � aperiente, estimula a digest�o, baixa a press�o arterial, apoia a circula��o do sangue e utiliza-se como antibi�tico, analg�sico e rem�dio anti-reum�tico. Dependendo da esp�cie, pode ser colhida entre Julho e Setembro. � apanhada quando as folhas est�o murchas. Pode ser preparada fresca ou atada aos molhos, pendurada num s�tio seco ou guardada no frigor�fico durante longos per�odos. '),
cozinha('Utiliza-se a cebola para dar um sabor especial a todo o tipo de pratos de carne e ainda a comi das � base de ovos, saladas e sopas, como, por exemplo, a sopa de legumes e a sopa goulasch. Tamb�m se pode preparar uma pasta � base de cebolas e de condimentos, que deve ser fresca. Pode-se-lhe acrescentar um pouco de sumo de lim�o, porque a cebola crua ganha um sabor amargo quando est� muito tempo em contacto com o ar.'),
saude('Cebolas cruas s�o indicadaspara o tratamento de inflama��es dos sistemas respirat�rio e urin�rio, e, tamb�m, para casos de infec��es intestinais. Ajudam a manter o n�vel do colesterol baixo, estimulam o apetite e a digest�o, e previnem infec��es na boca. Uma cataplasma de cebolas limpa o pus das feridas. Esfregar a pele com sumo de cebola � um rem�dio caseiro eficaz no tratamento de picadas de insectos. Na cosm�tica � base de produtos naturais, a cebola � aplicada em tinturas diluidas para remover impurezas da pele e estimular o crescimento do cabelo. Tamb�m c considerada um afrodis�aco. O cebolinho (allium fistulosum), parente pr�ximo da cebola, acua como erva sudor�fera e carminativa, e ajuda a secar fur�nculos e abcessos.')).

record(nome('ALLIUM SATIVUM'),
nomescomum('Alho'),
sinonimo('None'),
familia('Ali�ceas (Alliaceae).'),
origem('�sia Central.'),
historia('O alho � considerado uma das mais antigas plantas medicinais. Ter� tido um papel importante na alimenta��o em algumas culturas; o historiador grego Her�doto refere que o alho era dado aos trabalhadores da constru��o da pir�mide de Qu�ops, para os ajudar a recuperar as for�as. Antes da inven��o do antibi�tico, usava-se o alho para tratar as mais variadas infec��es  da tuberculose ao tifo. Durante a Primeira Guerra Mundial ainda servia frequentemente para tratar feridas.'),
floracao('De Junho a Agosto.'),
caracteristica('Planta vivaz, com altura at� 1 metro e flores brancas ou rosa-claras. As folhas, roli�as na base, ocas e achatadas na parte superior, crescem a partir de um bolbo que, no fim do per�odo de crescimento, desenvolve outros pequenos bolbos, aos quais chamamos �dentes de alho�.'),
habitat('A planta � provavelmente origin�ria de regi�es �ridas da �sia Central e �, hoje em dia, cultivada um pouco por todo mundo. Plantada no jardim, requer um s�tio protegido e soalheiro, bem como um solo perme�vel.'),
propriedades('Atribu�-se ao alho um efeito anti-s�ptico, expectorante, sudor�fero, anti-hipertensor e anticoagulante. Ajuda a baixar os n�veis de a��car no sangue. � rico em vitaminas A, B, C, e E. O alho � colhido depois de as ramas secarem, devendo ser colocado uns dias ao sol. A seguir, � atado em molhos e pendurado num lugar arejado e � sombra. O alho pode tamb�m ser conservado em �leo ou vinagre.'),
cozinha('Os dentes de alho picados conferem um sabor inconfund�vel aos pratos de carne, aos molhos e �s sopas, sendo imprescind�veis no preparado de manteiga de ervas. Nas saladas, basta esfregar o interior da saladeira com alho.'),
saude('o alho � um rem�dio caseiro antigo e conhecem-se os seus numerosos efeitos ben�ficos, por exemplo, em casos de infec��es das vias respirat�rias, problemas de circula��o do sangue, n�veis de colesterol alto e hipertens�o arterial. O alho ajuda tamb�m a melhorar a digest�o e limpa os intestinos. Ingerido regularmente, poder� prevenir altera��es dos vasos sangu�neos, resultantes do avan�o da idade. Quem evita ingerir alho por causa do h�lito poder� comer, depois de uma refei��o, salsa fresca em abund�ncia, pois esta ajudar� a disfar�ar o cheiro.')).

record(nome('ALLIUM SCHOENOPRASUM'),
nomescomum('Cebolinho, Ceboleta-de-fran�a'),
sinonimo('None'),
familia('Ali�ceas (Alliaceae).'),
origem('Europa e �sia.'),
historia('None'),
floracao('De junho a Julho.'),
caracteristica('� uma planta que pode atingir os 30 cm de altura, apresentando folhas roli�as e arom�ticas com cap�tulos roxos. Existem v�rias esp�cies que se distinguem sobretudo atrav�s da espessura das folhas.'),
habitat('j� h� muito tempo que o cebolinho � uma planta dom�stica. Nos jardins, necessita de um lugar com sol e meia-sombra e de um solo rico em nutrientes (de prefer�ncia calc�rio). O cebolinho tamb�m cresce em casa, em vasos � janela, onde pode ser colhido durante todo o ano. Nos campos, � poss�vel encontrar cebolinho bravio.'),
propriedades('o cebolinho, tal como a cebola e o alho, � rico em vitamina C e em minerais, contribuindo, desta forma, para o bom funcionamento do nosso organismo. As folhas longas e tubulosas encontram-se em crescimento constante e devem ser cortadas rente ao solo, entre Abril e Outubro. Podem ser utilizadas frescas ou congeladas. N�o � aconselh�vel sec�-las, pois perdem n�o s� a cor como tamb�m grande parte do seu aroma.'),
cozinha('O cebolinho � muito apreciado em saladas, pratos de legumes, ovos, carne e peixe, caldeiradas, ovos mexidos, molhos com natas e queijo quark. Picado, serve para barrar p�o e � utilizado como elemento decorativo em sopas.'),
saude('o cebolinho serve sobretudo para estimular o apetite e a digest�o.')).

record(nome('ALLIUM TUBEROSUM'),
nomescomum('Cebolinho chin�s'),
sinonimo('None'),
familia('Ali�ceas (Alliaceae).'),
origem('�ndia, Jap�o, Nepal e China.'),
historia('None'),
floracao('De Agosto a Setembro.'),
caracteristica('� uma planta perene que pode atingir os 40 cm. Possui folhas planas que, contrariamente �s do cebolinho, n�o s�o ocas. A in�loresc�ncia consiste numa umbela de flores brancas em forma de estrela, que s�o polinizadas por abelhas e z�ng�os. Toda a planta exala um ligeiro aroma a alho.'),
habitat('Esta planta perene pode cultivar-se quer em jardins, onde necessita de sol quer em s�tios com meia-sombra, com um solo pierme�vel e rico em nutrientes, ou ainda em vasos � janela.'),
propriedades('O cebolinho chin�s possui propriedades semelhantes �s da sua parente pr�xima, a cebola, e �s do alho. Deve ser consumido sempre fresco.'),
cozinha('As folhas do cebolinho chin�s possuem um aroma parecido com o da cebola e com o do alho, mas menos intenso. Picadas e frescas, s�o empregadas em molhos, saladas, pratos frios e de peixe, e, ainda, em pratos de ovos e de batatas. Acrescentando cebolinho chin�s picado a queijo quark ou a outro tipo de queijo, obt�m-se um saboroso creme para barrar o p�o. Juntando folhas secas de cebolinho chin�s, manjerico, manjerona e salsa, consegue-se uma mistura picante de ervas. O cebolinho chin�s � um condimento muito utilizado na culin�ria asi�tica.'),
saude('O cebolinho chin�s � famoso por estimular o apetite e a digest�o.')).

record(nome('ALLIUM URSINUM'),
nomescomum('Alho-de-urso'),
sinonimo('None'),
familia('Ali�ceas (Alliaceae).'),
origem('Europa.'),
historia('O valor que os nossos antepassados atribu�am a esta planta � evidente neste velho ditado alem�o: �Come alho-porro na Primavera e alho-de-urso em Maio e n�o ver�s o m�dico durante todo o ano.�'),
floracao('De Abril a Junho.'),
caracteristica('o alho-de-urso � uma planta perene que emana um cheiro intenso a alho, podendo atingir os 50 cm de altura. O caule � triangular e dele brotam folhas basilares lanceoladas ou ovais, com pec�olos curtos, apresentando uma cor verde-escura na p�gina superior e uma tonalidade mais clara na p�gina inferior.'),
habitat('O alho-de-urso encontra-se preferencialmente em bosques h�midos e sombrios, onde cresce de forma densa.'),
propriedades('a planta contribui para a purifica��o do corpo, revelando propriedades diur�ticas, depurativas, anti-hipertensoras e anti-s�pticas. O alho de urso costuma ser utilizado fresco, mas tamb�m pode estar congelado ou seco. Deve colher-se antes de florir.'),
cozinha('O paladar do alho-de-urso lembra o do alho, mas n�o � t�o intenso nem causa o mesmo h�lito. As folhas picadas servem para refinar o sabor de sopas, saladas, molhos e legumes.'),
saude('Como rem�dio caseiro, emprega-se o alho-de-urso cm casos de dispepsia, flatul�ncia e c�licas. Tamb�m estimula o apetite, fortalece o aparelho digestivo, baixa a tens�o arterial e reduz os riscos de arteriosclerose.')).

record(nome('ALOE VERA'),
nomescomum('Alo�, Babosa'),
sinonimo('Aloe barbadensis.'),
familia('Lili�ceas (Liliaceae).'),
origem('�frica.'),
historia('O alo� � conhecido h� muito tempo como ingrediente de lo��es para a pele. Diz-se que Cle�patra, tal como muitas outras mulheres, devia em parte a sua extraordin�ria beleza a esta planta.'),
floracao('De Maio a Junho.'),
caracteristica('Trata-se de uma planta perene que pode atin gir os 60 cm de comprimento, com folhas verde acinzentadas, espinhosas e suculentas, e com flores amarelas ou cor-de-laranja, dispostas em pan�cula.'),
habitat('Esta planta, origin�ria da �frica Austral e da �frica Oriental, � hoje cultivada em muitas regi�es tropicais para fins comerciais. Na Europa, � conhecida por ser uma planta de vaso, pouco exigente. Muitas outras variedades de alo� servem igualmente tins medicinais, como por exemplo o Aloeferox.'),
propriedades('O alo� � cicatrizante, estimula a secre��o biliar e actua como laxante. Utilizam-se tamb�m os seus extractos com propriedades emolientes (tornam a pele male�vel e macia]. Para extrair o suco espesso desta planta, cortam-se as pontas das folhas. Alo�s plantados em vasos podem, contudo, perder parte substanciai do seu efeito medicinal.'),
cozinha('None'),
saude('O suco viscoso do alo� � geralmente aplicado em casos de queimaduras, escoria��es e escald�es. Cautelosamente, esfregam-se com essa subst�nciaas zonas da pele afectadas, de modo a aliviar a dor e a prevenir infec��es. Na ind�stria cosm�tica, o alo� aplica-se em cremes para m�os e rosto, assim como em champ�s e em protectores solares.')).

record(nome('ALTHAEA OFFICINALIS'),
nomescomum('Alteia'),
sinonimo('None'),
familia('Malv�ceas (Malvaceae).'),
origem('Europa, Asia e �frica do Norte.'),
historia('J� na antiguidade, o fil�sofo grego Teofrasto relatava a efic�cia da mistura de alteia e vinho como rem�dio para a tosse.'),
floracao('De Junho a Setembro.'),
caracteristica('� uma planta perene que pode atingir 1,5 m de altura. Possui uma raiz branca e forte, assim como caules erectos e pilosos. As folhas trilobadas t�m peciolos curtos e uma base cordiforme. As flores, de cor  branca ou rosa-claro, encontram-se dispostas em cachos terminais ou axilares.'),
habitat('A alteia tem prefer�ncia por solos salinos e h�midos, como, por exemplo, os que se situam perto da costa litoral. A�, cresce de forma bravia. � cultivada em grande quantidade, para fins medicinais. No jardim, necessita de sol e de terra h�mida e compacta.'),
propriedades('A alteia possui propriedades anti-inflamat�rias, expectorantes e laxantes. As folhas podem ser colhidas entre Maio e Agosto, as flores assim que come�am a abrir, enquanto as ra�zes de Outubro at� � Primavera seguinte. Todas as partes podem ser lentamente secas � sombra.'),
cozinha('As ra�zes frescas de plantas bienais podem ser preparadas como se fossem batatas e as folhas jovens como se fossem legumes. Quanto �s sementes, podem ser adicionadas a saladas.'),
saude('A raiz � considerada um bom rem�dio para a tosse, sobretudo quando se trata de crian�as. Tamb�m � utilizada para produzir elixires e pomadas ou para tratar fur�nculos e abcessos. Uma infus�o de alteia acelera a cura da pele quando est� irritada por um escald�o.')).

record(nome('ANETHUM GRAVEOLENS'),
nomescomum('Endro, Aneto'),
sinonimo('None'),
familia('Api�ceas (Apiaceae).'),
origem('A origem � desconhecida, uma das ervas mais antiga'),
historia('O endro j� era utilizado no antigo Egipto. Uma receita medicinal relatada no papiro Ebers [cerca de 1600 a. C.) recomenda o endro como analg�sico. Na Gr�cia antiga, colocava-se a planta nos olhos para ajudar a adormecer. Na Idade M�dia, julgava-se que queimar endro afastava as nuvens da trovoada. O termo alem�o para endro � "dill", deriva do arcaico "dylla", que significa aliviar, acalmar.'),
floracao('De Julho a Setembro.'),
caracteristica('Planta herb�cea, anual, com caule erecto e fistuloso. Pode atingir os 75 cm de altura. As folhas possuem peciolos que alargam na base, formando uma bainha, envolvendo o caule. As folhas s�o, portanto, invaginantes. As numerosas flores amarelas encontram-se ordenadas em umbelas, que podem atingir 15 cm de largura. A planta exala um cheiro arom�tico muito t�pico, enquanto os frutos leves revelam um sabor picante.'),
habitat('Esta antiga planta de cultivo precisa de sol e de meia-sombra, exigindo um solo pouco seco e perme�vel. Na Europa Central, pode-sc encontrar endro bravio � beira dos caminhos, na orla de terras ar�veis e em �reas de pousio.'),
propriedades('o endro estimula a digest�o, � carminativo, diur�tico e arom�tico. Para a sua prepara��o, utilizam-se as pontas dos rebentos e as sementes. A planta pode ser colhida at� ao Outono e utilizada fresca ou congelada. Tamb�m pode ser seca mas, nesse caso, corre-se o risco de se perder parte do aroma. As sementes s�o colhidas quando a cor das umbelas muda para castanho.'),
cozinha('As folhas do endro servem para refinar o sabor de sopas, de molhos e de todo o tipo de pratos de peixe ou de carne (como, por exemplo, peixe cozido ou carne de borrego). Tamb�m conferem um sabor requintado a pratos frios, pratos de ovos ou queijo quark, a saladas de tomate ou de pepino e � confec��o de manteiga de ervas. As umbelas e as sementes s�o um �pimo tempero para preparar pepinos em conserva. As sementes maduras mo�das s�o igualmente um excelente condimento, podendo ser empregadas como alternativa aos cominhos. O �leo e o vinagre ficam com um sabor requintado quando se misturam com endro.'),
saude('o endro � uma erva medicinal muito apreciada. � considerado um rem�dio para a tosse, a gripe e as constipa��es. � carminativo e alivia c�licas intestinais. Mastigar as sementes disfar�a o mau h�lito. O endro poder� tamb�m aumentar o leite materno e evitar c�licas nos beb�s, quando tomado regularmente durante a gravidez. Para uso externo, � indicado em casos de �lceras e inflama��es nos olhos. Mergulhar as m�os e os p�s numa infus�o de endro fortalece as unhas.')).

record(nome('ANGELICA ARCHANGELICA'),
nomescomum('Ang�lica, Erva-piolheira'),
sinonimo('None'),
familia('Api�ceas (Apiaceae).'),
origem('A dissemina��o desta planta abrange a Europa Centr'),
historia(' '),
floracao('De Junho a Agosto'),
caracteristica('Planta bienal e arom�tica com caule vermelho, fistuloso e sulcado. Pode atingir os 2 m de altura. Possui folhas grandes, pinuladas e bi ou trifoliadas, de cor verde-clara. As flores brancas-esverdeadas est�o dispostas em umbelas. A planta possui um cheiro intenso e arom�tico e um sabor picante e amargo.'),
habitat('Em jardins, gosta preferencialmente de um s�tio ao sol ou com meia-sombra e de um solo que n�o seja demasiado seco. Na Europa Central, cresce bravia e gosta de terra h�mida, como, por exemplo, a que se encontra perto de rios e ribeiros, desfiladeiros e bosques pouco secos.'),
propriedades('Actua como anti-s�ptico, estimula o apetite e adigest�o e � antiespasm�dica. Os caules e as folhas s�o colhidos no in�cio do Ver�o, enquanto as sementes se apanham depois de amadurecerem, tamb�m no Ver�o, e as ra�zes no fim do Outono do segundo ano (j� com as folhas murchas). As ra�zes e as sementes podem tamb�m ser conservadas secas.'),
cozinha('Caules e folhas frescas podem ser aproveitados como condimento para sopas, molhos e saladas. As ra�zes servem para a produ��o de ch�s, licores e aguardente de ervas.'),
saude('A ang�lica � indicada como t�nico e � empregada no al�vio de indisposi��es estomacais, gases e c�licas, bem como na melhoria da circula��o do sangue.')).

record(nome('ANTHRISCUS CEREFOLIUM'),
nomescomum('Ceref�lio, Salsa-de-burro'),
sinonimo('Anthriscus trichospermus.'),
familia('Api�ceas (Apiaceae).'),
origem('Europa do Sul �sia e �frica do Norte.'),
historia('Foram encontrados pequenos recipientes com ceref�lio no t�mulo de Tutankhamon, o que revela o qu�o apreciada era esta planta no antigo Egipto. Provavelmente, foram os romanos que a trouxeram para a Europa Central.'),
floracao('De Maio a Agosto.'),
caracteristica('Trata se de uma planta anual que pode atingir os 60 cm de altura. Possui um caule fistuloso e canelado, bem como folhas pinuladas verde-claras. As tlores, pequenas e brancas, est�o dispostas em umbelas. Destaca-se o sabor t�pico e intenso a anis.'),
habitat('Pode-se encontrar o ceref�lio � beira de caminhos e em terrenos baldios. Plantado em jardins, necessita de sol ou de meia-sombra, bem como de um solo com boa drenagem, ligeiramente h�mido.'),
propriedades('o ceref�lio estimula a digest�o e actua como diur�tico e depurativo. Pode ser colhido entre meados de Maio e finais de Novembro. N�o � pr�prio para ser guardado.'),
cozinha('As folhas frescas e arom�ticas podem ser utilizadas como tempero em molhos (como, por exemplo, o �molho verde de Frankfurt�), em sopas e em diversos pratos, inclusive pratos de carne de bor rego, de peixe, de queijo "quark" e de ovos. Servem tamb�m para preparar vinagre e uma saborosa sopa de ceref�lio.'),
saude('A erva actua de forma ben�fica sobre o aparelho digestivo e ajuda a diminuir a tens�o arterial. O suco de ceref�lio fresco � ben�fico em casos de problemas cut�neos, nomeadamente eczemas e abcessos, mas tamb�m em feridas. Uma infus�o feita a partir das flores pode ser utilizada na cosm�tica, em m�scaras faciais e na limpeza da pele.')).

record(nome('APIUM GRAVEOLENS'),
nomescomum('Aipo, Raba�a'),
sinonimo('None'),
familia('Api�ceas (Apiaceae).'),
origem('Europa, �sia e �frica do Norte.'),
historia('H� registos que relatam o cultivo do aipo h� 3000 anos no Egipto e, desde o s�culo v a. C., tamb�m na China. Na antiga Gr�cia e na antiga Roma, o aipo deve ter desempenhado um papel nos rituais f�nebres, pois aparece em in�meros t�mulos. Chegou � Europa Central provavelmente apenas na Idade M�dia.'),
floracao('De Julho a Setembro.'),
caracteristica('Planta bienal, desenvolve poucas folhas no primeiro ano, podendo chegar a atingir 1 metro de altura no segundo. Possui um caule fistuloso, folhas com pec�olos longos, pinuladas e com margem dentada, assim como flores pequenas brancas em umbelas, que se desenvolvem apenas no segundo ano. � de destacar o forte aroma que emana de toda a planta.'),
habitat('o aipo, uma planta de cultivo milenar, cresce naturalmente em solos salinos. No jardim, requer terra h�mida e rica em nutrientes.'),
propriedades('o aipo actua como rem�dio anti-reum�tico, diur�tico e anti-hipeitensor, sendo ainda antiespasm�dico e carminativo. E tamb�m considerado um bom anti-s�ptico, no que diz respeito a problemas das vias urin�rias e da zona genital. Os tub�rculos e os pec�olos engrossados s�o cortados entre Outubro e Novembro, antes das primeiras geadas. Os tub�rculos conservam-se bem, durante algum tempo, num lugar fresco. Para uso medicinal, podem ser secos e guardados num recipiente hermeticamente fechado. Pode-se embrulhar em papel de jornal o aipo que n�o foi consumido ap�s a colheita, guardando-o num lugar fresco. Tamb�m � poss�vel congel�-lo para ser cozido. As folhas devem ser cortadas e consumidas na altura, mas se houver sobras podem ser congeladas ou secas.'),
cozinha('Existem algumas variedades de aipo, entre as quais se destaca o aipo pequeno (A.graveolens var. secalinum), que tem nonnalmente raiz fina e folhas particularmente arom�ticas. Estas s�o utilizadas em sopas e, quando secas, servem para fazer sal de aipo. O aipo-r�bano (A. graveolens var. rapaceum) possui uma raiz carnuda, que pode ser usada crua, em saladas. O aipo-de-talo (A. graveolens var. dulce) disp�e de pec�olos espessos, que podem ser preparados como legumes e acompanhar pratos frios e entradas servidas com cerveja.'),
saude('O aipo � considerado um diur�tico. As suas sementes eram utilizadas antigamente para tratar problemas de bexiga, problemas renais e tamb�m no al�vio do reumatismo e da artrite. A planta, � qual j� desde a antiguidade � atribu�do um efeito afrodis�aco, j� n�o � t�o frequentemente usada para fms medicinais. Visto ser rica em vitaminas e sais minerais, serve sempre para completar a alimenta��o.')).

record(nome('ARMORACIA RUSTICANA'),
nomescomum('R�bano-r�stico'),
sinonimo('None'),
familia('Brassic�ceas (Brassicaceae).'),
origem('Europa do Sul e Oriental.'),
historia('None'),
floracao('De Maio a Julho.'),
caracteristica('� uma planta perene com raiz aprumada, carnuda e longa, que sustenta um caule esquinado e sulcado. Pode atingir 1 metro de altura. As folhas basilares s�o grandes, longas e ovais, com margem crenada, enquanto as folhas caulinares s�o pinuladas. As pequenas flores brancas encontram-se dispostas em cachos'),
habitat('O r�bano-r�stico cresce de forma bravia em prados e � beira de caminhos. No jardim, � frequentemente cultivado como planta anual. E uma planta que requer sol e meia-scm�bra e terra h�mida, rica em nutrientes.'),
propriedades('O r�bano � conhecido por aumentar a transpira��o, estimular a digest�o e possuir efeitos anti-reum�ticos e diur�ticos. A raiz � colhida no Outono e pode ser conservada temporariamente num lugar escuro e h�mido, coberta de areia.'),
cozinha('o r�bano-r�stico serve para temperar molhos e para acompanhar pratos de carne e de peixe. � tamb�m um bom ingrediente para preparados de maionese ou de mostarda.'),
saude('A planta possui qualidades terap�uticas, destacando-se os seus efeitos diur�tico, digestivo e sudorifero, que a tornam indicada para casos de febre, constipa��es e gripe. A raiz � vulgamente usada como rem�dio caseiro contra a rinite al�rgica, podendo  ser picada fresca e ingerida com p�o. A raiz mo�da pode ser utilizada em compressas para aliviar frieiras (n�o abertas).')).

record(nome('ARNICA MONTANA'),
nomescomum('Arnica, Craveiro-dos-alpes'),
sinonimo('None'),
familia('Aster�ceas (Asteraceae)'),
origem('Europa'),
historia('None'),
floracao('De Junho a Julho.'),
caracteristica('Trata se de uma planta perene, arom�tica, que pode atingir 60 cm de altura. Possui um rizoma casta nho, um caule piloso e uma roseta-basilar, composta por folhas lanceoladas ov�ides. A infloresc�ncia � constitu�da por pequenas br�cteas interflorais amarelas e grandes br�cteas involucrais laranja-amareladas.'),
habitat('Na Europa Central,  a arnica cresce em prados e bosques, situados nas montanhas. Chamamos a aten��o para o facto de se tratar de uma planta protegida em pa�ses como a Alemaha, a �ustria e a Su��a, raz�o pela qual n�o pode ser colhida. Cultivada no jardim, necessita de sol e de um solo sem calc�rio.'),
propriedades('A arnica caracteriza-se por ser uma erva anti-s�ptica e anti-reum�tica que previne a artrite. As flores s�o colhidas entre Junho e Agosto e o rizoma no Outono, ap�s as folhas murcharem.'),
cozinha('None'),
saude('A arnica era antigamente uma planta medicinal muito conhecida. Consideravam-na um estimulante da circula��o sangu�nea e um excelente rem�dio para a angina de peito, "angina pectoris" (o poeta alem�o Goethe bebia ch� de arnica em idade avan�ada, para aliviar a sua angina de peito). Sabemos hoje que a arnica cont�m subst�ncias t�xicas em quantidades consider�veis, raz�o pela qual o seu uso � actualmente apenas externo. O efeito anti-s�ptico da pomada de arnica mostra-se eficaz no tratamento de contus�es,  entorses e dores musculares, melhorando a irriga��o sangu�nea nas partes lesionadas e acelerando a cura.')).

record(nome('ARTEMISIA ABROTANUM'),
nomescomum('Abr�tano'),
sinonimo('None'),
familia('Aster�ceas (Asteraceae).'),
origem('�sia Menor e possivelmente tamb�m na Europa do Sul'),
historia('O nome cient�fico desta planta prov�m da rainha persa Artem�sia, que, segundo consta, ter-se-� interessado por bot�nica. O abr�tano chega � Europa Central por volta do s�c. IX ou X, onde � cultivado nos jardins dos mosteiros. Na �poca da ca�a �s bruxas, acusavam-nas de usar o abr�tano para fabricar po��es m�gicas.'),
floracao('De julho a Outubro.'),
caracteristica('Trata-se de uma planta perene, que pode atingir 1 metro de altura e apresenta folhas verde-acinzentadas, pinuladas e lanceoladas, bem como flores pequenas, amareladas e dispostas em infloresc�ncias paniculadas. A planta caracteriza-se pelo cheiro a lim�o das folhas.'),
habitat('Em cultivo, a planta requer um lugar com sol ou meia-sombra e um solo perme�vel, preferencialmente rico em calc�rio.'),
propriedades('A planta � conhecida por ser tonificante e tamb�m repelente de insectos. Os rebentos frescos podem ser colhidos entre a Primavera e o Outono e utilizados frescos ou secos.'),
cozinha('O abr�tano pode ser empregado em pequenas quantidades como condimento. Neste caso, utilizam-se as pontas das folhas frescas ou secas para refinar o sabor de molhos ou temperar pratos gordos, como, por exemplo, pato assado.'),
saude('A planta tem propriedades digestivas. Colocada num roupeiro, repele as tra�as, e, plantada no jardim, pode afastar a borboleta branca da couve.')).

record(nome('ARTEMISIA ABSINTHIUM'),
nomescomum('Absinto, Sant�nica, Amargoso, Erva-das-sez�es'),
sinonimo('None'),
familia('Aster�ceas (Asteraceae)'),
origem('Europa e �sia.'),
historia('Antigamente, esta planta era utilizada na produ��o de absinto, uma bebida t�xica e viciante, muito popular na Fran�a do s�c. XIX. Depois de se registrarem v�rios casos de graves complica��es de sa�de devido ao consumo do absinto, este foi finalmente proibido.'),
floracao('De julho a Setembro.'),
caracteristica('Planta perene, que pode atingir 1,2 m de altura, com caules verde acinzentados, folhas pinuladas densa mente pilosas e flores pequenas e amarelas, dispostas em pan�cula. Caracteriza-se pelo cheiro arom�tico forte e pelo sabor muito amargo.'),
habitat('Na Europa Central, o absinto bravio cresce em lugares secos, � beira de caminhos e em terrenos em pousio. O absinto cultivado no jardim precisa de sol ou de meia-sombra e de terra perme�vel.'),
propriedades('O absinto caracteriza-se por ser arom�tico, amargo, digestivo e estimulante. De Maio a Outubro, podem colher-se os rebentos. Para secar a planta, deve-se colh�-la antes da flora��o.'),
cozinha('O absinto � muito apreciado como aroma de bebidas alco�licas. Em pequenas quantidades, pode ser utilizado para refinar o sabor de pratos de carne ou de caldeiradas. Tamb�m pode ser �til como repelente.'),
saude('O absinto amargo - em latim, absinthium significa desagrad�vel - actua beneficamente sobre o aparelho digestivo, nomeadamente, o est�mago e a ves�cula biliar.')).

record(nome('ARTEMISIA DRACUNCULUS'),
nomescomum('Estrag�o, Erva-drag�o'),
sinonimo('None'),
familia('Aster�ceas (Asteraceae).'),
origem('Sul da R�ssia e �sia Central.'),
historia('O estrag�o � mencionado, pela primeira vez, em documentos chineses datados de 3000 a. C. Da China foi levado para o mundo �rabe e, na �poca das cruzadas, tamb�m chegou � Europa.'),
floracao('De julho a Outubro.'),
caracteristica('Trata-se de uma planta perene, que pode alan�ar  1 metro de altura, com folhas lanceoladas e s�sseis ou com peciolos curtos, e com pequenos cap�tulos discretos, de cor branca esverdeada. Exala um cheiro tipicamente arom�tico.'),
habitat('O estrag�o � cultivado um pouco por todo o mundo. Requer terra perme�vel, h�mida e rica em nutrientes. Precisa de um lugar quente e abrigado do vento e necessita de protec��o no Inverno.'),
propriedades('O estrag�o � conhecido como uma eiva arom�tica I	e digestiva. As folhas destinadas a ser guardadas podem ser colhidas entre Maio e Junho. Os rebentos em flor colhem-se entre Julho e Agosto. Para secar esta en-a, deve-se escolher um lugar � sombra e arejado. Para a guardar, utilizam-se recipientes de vidro ou porcelana.'),
cozinha('As folhas frescas de estrag�o s�o indicadas para refinar o sabor de sopas, molhos, queijo quark, saladas e pratos de carne de ave. Podem tamb�m ser utilizadas no preparo de vinagre de ervas, licor de ervas ou mostarda. Recomendam-se, entre as diversas variedades existentes, as de estrag�o franc�s ou alem�o, muito apreciadas devido ao seu paladar mais arom�tico.'),
saude('O estrag�o estimula o apetite e a digest�o e pode ser tamb�m utili zado como calmante e soporifero. Antigamente, em casos de dores de dentes, mastigava-se a raiz.')).

record(nome('ARTEMISIA VULGARIS'),
nomescomum('Artem�sia, Erva-de-fogo'),
sinonimo('None'),
familia('Aster�ceas (Asteraceae).'),
origem('Europa, �sia, �frica do Norte.'),
historia('A artem�sia ter� sido utilizada pelos romanos para forrar as suas sand�lias, de modo a manterem os p�s saud�veis.'),
floracao('De Agosto a Novembro.'),
caracteristica('Trata se  de uma planta arom�tica e perene, podendo atingir 1,5 m de altura. Apresenta folhas pinuladas, verde-escuras e alter nas, cujo lado inferior � lanoso e de cor branca. Os cap�tulos, dispostos em pan�cula, s�o pequenos e apresentam uma cor que varia entre o averme� lhado e o amarelo.'),
habitat('A artem�sia est� espalhada por vastas �reas da Europa e cresce preferencialmente em terrenos baldios, � beira dos caminhos e junto a arbustos. Cultivada, revela-se pouco exigente na manuten��o, apenas necessitando de sol.'),
propriedades('A artem�sia � uma erva amarga, sedativa e arom�tica, que estimula o apetite e a digest�o. As folhas e os rebentos podem ser colhidos at� a planta florir. Pan�culas destinadas a serem secas cortam-se pouco antes da floresc�ncia, no final do Ver�o.'),
cozinha('Folhas frescas ou secas s�o ideais para pratos gordos, como, por exemplo, pratos de carne de porco, borrego ou pato e saladas.'),
saude('A artem�sia � aperiente, digestiva e � mais suave do que as suas parentes, pelo que poder� ser ingerida em forma de ch� durante longos per�odos.')).

record(nome('BARBAREA VULGARIS'),
nomescomum('Erva-de-Santa-B�rbara, Erva-dos-carpinteiros'),
sinonimo('None'),
familia('Brassic�ceas (Brassicaceae).'),
origem('Europa, �sia e �frica do Noite.'),
historia('A planta deve o seu nome ao facto de ficar verde e comest�vel a partir do dia 4 de Dezembro, dia de Santa B�rbara.'),
floracao('De Abril a Julho.'),
caracteristica('Trata-se de uma planta bienal, que pode atingir os 90 cm de altura. Possui um caule ramificado, com folhas basilares ovadas e folhas caulinares pinuladas. As infioresc�ncias s�o compostas por tlores de cor amarelo-vivo.'),
habitat('Pode-se encontrar a planta em prados, � beira de caminhos ou nas orlas de terras cultivadas, bem como nas margens de rios e ribeiros. No jardim, requer um s�tio pouco seco com meia-sombra. Tamb�m pode ser cultivada numa estufa fria.'),
propriedades('Caracteriza-se por estimular o metabolismo e purifiar o organismo. � rica em vitaminas e sais minerais. Trata-se de uma erva que tamb�m est� dispon�vel no Inverno.'),
cozinha('As folhas em roseta basilar, apanhadas entre Dezembro e Maio, podem ser preparadas e cozinhadas como os espinafres. As folhas caulinares s�o colhidas na Primavera e servem para saladas (a mistura com folhas de outras plantas disfar�a o sabor um pouco forte). Tamb�m � ideal para dar um toque especial ao queijo e ao queijo quark, � manteiga de ervas e a sopas leves.'),
saude('Dado ser rica em vitamina C, era, em tempos, ingerida para combater o escorbuto. Hoje em dia, � apreciada pelo seu efeito diur�tico, cicatrizante, estimulante do apetite e purificador do sangue.')).

record(nome('BORAGO OFFICINALIS'),
nomescomum('Borragem, Borago'),
sinonimo('None'),
familia('Borogin�ceas (Boroginaceae).'),
origem('�, provavelmente, oriunda do Mediterr�neo.'),
historia('Antigamente, pensava-se que afastava a tristeza, por isso, o s�bio romano Pl�nio afirmava que a borragem �traz sempre alegria�.  Tamb�m nos livros	medievais sobre ervas, esta planta era apresentada como rem�dio para a melancolia.'),
floracao('De Maio a Agosto.'),
caracteristica('Planta	anual,  que pode atingir os 60 cm de altura, com um caule ramificado e hispido.  As folhas basilares s�o grandes, ovais, inteiras ou dentadas; as folhas caulinares s�o lanceoladas e pilosas. As flores azuis e vistosas formam unia panicula ligeiramente ramificada.'),
habitat('Na Europa Central, apenas cresce de forma selvagem em campos, prados e terrenos baldios. Cultivada no jardim, requer sol e terra perme�vel, rica em nutrientes, de prefer�ncia calc�rio.'),
propriedades('A planta possui propriedades diur�ticas, anti-reum�ticas, anti-in�lamat�rias, sudor�feras e expectorantes.'),
cozinha('Na culin�ria, utilizam-se geralmente os rebentos, as folhas e as flores, que s�o colhidos entre Maio e Outubro e preparados ainda frescos, podendo tamb�m ser congelados. As folhas s�o usadas na confec��o de salada de pepino ou outras, assim como na prepara��o do �molho verde de Frankfurt�.'),
saude('A planta � rica em mucilagem, aliviando problemas relacionados com as vias respirat�rias. As flores t�m propriedades diur�ticas e sudor�feras. O �leo extra�do da semente da planta � rico em �cidos gordos poliinsaturados, usados no tratamento de eczemas e de outras doen�as cut�neas cr�nicas.')).

