record(nome('ACHILLEA MILLEFOLIUM'),
nomescomum('Milefolio, Erva-carpinteira, Macela-de-Sao-Joao'),
sinonimo('None'),
familia('Asteraceas (Asteraceae)'),
origem('Europa'),
historia('O milefolio ja era utilizado na antiguidade para tratamento de ferimentos de guerra, podendo, por isso, tambem chamar-se herba militaris (Erva-dos-soldados)'),
floracao('De junho a Outubro.'),
caracteristica('Trata-se de uma planta aromatica, com uma altura que pode chegar aos 60 cm e com caules erectos e lanosos. As folhas alternas e duplamente penatipartidas tem um tom verde acizentado.A inflorescencia e formada por  uma panicula em forma de umbela, apre sentando flores do disco amarelas (no interior) e flores liguladas brancas ou rosa (no exterior).'),
habitat('O milefolio cresce em solos ricos em azoto, a beira de caminhos, em prados, campos secos e terrenos baldios. Cultivado em jardins, nao e muito exigente e apenas necessita de sol.'),
propriedades('o milefolio possui qualidades calmantes e anti-espasmodicas. A achilelna contida na planta tem um efeito cicatrizante. Os rebentos colhem-se a partir de Maio. A planta em flor colhe-se entre junho e Setembro. A secagem faz-se com as plantas atadas em molhos e penduradas num local arejado e a sombra.'),
cozinha('Rebentos e folhas frescas e picadas podem ser utilizados em saladas.'),
saude('Em casos de colicas e problemas relacionados com a digestao, a planta em flor pode ser empregada como tonico. Ajuda a tensao arterial a descer, contribui para uma melhor circulacao sanguinea, produzindo tambem um efeito benefico no caso de varizes e de rinite alergica, bem como durante o periodo menstrual. As flores deitadas em agua quente libertam vapores que revitalizam a pele do rosto.')).

record(nome('AGASTACHE FOENICULUM'),
nomescomum('Hissopo-anisado'),
sinonimo('Agastache anethiodora'),
familia('Lamiaceas (Larniaceae).'),
origem('America do Norte.'),
historia('Esta planta ja era conhecida pelos indigenas norte americanos devido aos seus valores nutritivo e medicinal. Foi introduzida na Europa por apicultores, pois as suas flores constituem uma excelente fonte de alimento para as abelhas.'),
floracao('De junho a Setembro.'),
caracteristica('Planta vivaz, resistente no Inverno, cujo caule pode atingir 90 cm de altura. Possui grandes inflorescencias de cor purpura e folhas verde-prateadas, com comprimento ate 8 cm, sabor adocicado e cheiro a anis.'),
habitat('Esta planta cresce bem em vasos ou no jardim, em sitios expostos ao sol ou em locais semi-sombrios, com solo permeavel. Na Europa Central nao necessita de ser protegida da geada.'),
propriedades('Destacam-se os efeitos anti-inflamatorios e digestivos. As folhas devem ser colhidas antes de a planta florir, e podem ser utilizadas frescas ou secas.'),
cozinha('As folhas frescas podem ser utiliza das na preparacao de saladas e na producao de licores; as flores sao um excelente elemento decorativo em saladas e sobremesas.'),
saude('A partir das folhas secas pode-se fazer um cha que alivia dores de garganta, constipacoes e que acalma o estomago. As flores, frescas ou secas, servem de decoracao em arranjos florais.')).

record(nome('ALCEA ROSEA'),
nomescomum('Malvaisco, Flor-de-pau'),
sinonimo('None'),
familia('Malvaceas (Malvaceae).'),
origem('Paises Mediterranicos.'),
historia('None'),
floracao('De Julho a Setembro.'),
caracteristica('No primeiro ano, o malvaisco desenvolve apenas uma roseta basilar. Na Primavera seguinte, formam-se os caules hirsutos, com uma altura ate 2,5 m. As folhas, palmatilobadas e tomentosas, apresentam uma base foliar cordiforme e margens dentadas. A cor das flores, que podem atingir 10 cm de largura, varia entre o vermelho, o rosa, o branco, o amarelo e o purpura-escuro.'),
habitat('Na terra de origem, a planta cresce em terrenos baldios, rochosos e junto as linhas ferreas. No jardim, porem, o mal vaisco necessita de um lugar com sol ou com meia-sombra, protegido do vento, e de um solo com nutrientes em abundancia.'),
propriedades('o malvaisco tem propriedades expectorantes e diureticas. Utilizam-se as raizes, as folhas e sobretudo as flores. Estas sao recolhidas pouco antes de desabrocharem, sendo que as flores escuras sao preferiveis as brancas e amarelas. Podem ser utilizadas frescas ou secas. Neste ultimo caso, devem ser guardadas num local escuro.'),
cozinha('Os corantes contidos nas flores podem ser aproveitados para colorir licores e alimentos.'),
saude('As flores do malvaisco fazem frequentemente parte dos ingredientes das infusoes para a tosse e para a bronquite. As infusoes podem ser utilizadas para gargarejar, aliviando inflamacoes da mucosa da boca e da garganta.')).

record(nome('ALCHEMILLA XANTHOCHLORA'),
nomescomum('Pe-de-leao, Mata-boi, Patalo-dos-vales'),
sinonimo('Alquemila vulgaris.'),
familia('None'),
origem('Europa.'),
historia('A designacao popular em alemao e em ingles — “capa de Senhora” — provem da forma das folhas, que, supostamente, faz lembrar a capa de Nossa Senhora, razao pela qual na Idade Media a planta era sugerida para resolver toda a especie de “problemas das mulheres”.'),
floracao('De Maio a Setembro.'),
caracteristica('Trata-se de uma planta perene, que pode crescer ate 40 cm de altura, com uma roseta basilar de folhas pubescentes e palmatilobadas e com flores grandes, verdes e discretas, dispostas em paniculas arredondadas.'),
habitat('Cresce preferencialmente em campos e prados, mas tambem pode ser encontrada perto de florestas e em margens de rios, tratando-se de uma planta com grande disseminacao. Cultivada em jardins, nao requer muitos cuidados.'),
propriedades('o pe-de-leao possui qualidades adstringentes e anti-inflamatorias, sendo tambem ligeiramente anti-septico. As folhas devem ser colhidas entre Maio e Julho, e secas a sombra, devendo-se vira-las com frequencia.'),
cozinha('As folhas novas podem ser utilizadas em saladas.'),
saude('Como ja foi mencionado, o pe-de-leao e empregado como remedioeficaz nos «problemas das mulheres, aliviando inclusivamente dores menstruais muito fortes. Gracas ao seu efeito adstringente, estanca a perda de sangue e acelera o processo de cicatrizacao. O efeito adstringente tambem e util em casos de diarreia e de catarro intestinal.')).

record(nome('ALLIARIA PETIOLATA'),
nomescomum('Erva-alheira, Aliaria'),
sinonimo('Alliaria officinalis.'),
familia('Brassicaceas (Brassicaceae).'),
origem('Europa e Asia.'),
historia('None'),
floracao('De Abril a Maio.'),
caracteristica('Trata-se de uma planta que pode atingir 1 metro de altura, apresentando flores brancas e pequenas. As folhas basilares possuem peciolos longos e sao reniformes e crenadas, enquanto as folhas caulinares sao cordiformes ou deltoides, podendo ser sesseis ou possuir um peciolo curto.'),
habitat('Abunda na Europa Central, principalmente em clareiras, orlas de bosques, arbustos e  terrenos baldios. Em jardins, requer um lugar com meia-sombra e com solo permeavel.'),
propriedades('a erva-alheira possui propriedades expectorantes, actua ligeiramente como anti-septico e estimula a respiracao. Todas as partes da planta podem ser utilizadas. Deve ser colhida entre Maio e Julho e preparada no momento, pois nao e propria para ser guardada.'),
cozinha('Trata-se de uma planta que se adequa as mais variadas receitas. As tenras folhas proporcionam, devido ao seu ligeiro paladar a alho, um sabor especial em saladas, em queijo quark, em manteiga de ervas e em quiches. Picada, serve de conduto para o pao. A raiz pode ser preparada como o rabano-silvestre e as vagens podem servir para substituir a mostarda.'),
saude('Enquanto erva medicinal, desempenha um papel benefico, sobre tudo na area das vias respiratorias. Antigamente era utilizada, dado o seu efeito anti-septico, como elixir contra inflamacoes das gengivas.')).

record(nome('ALLIUM CEPA'),
nomescomum('Cebola'),
sinonimo('None'),
familia('Aliaceas (Alliaceae).'),
origem('Asia Ocidental.'),
historia('No Medio Oriente e na China, ja se cultiva cebola ha mais de mil anos. Chegou a Europa Central provavelmente com os romanos. Na Idade Media, pendurava-se cebolas por cima da porta para repelir a Peste Negra.'),
floracao('De Junho a Agosto.'),
caracteristica('Trata-se de uma planta perene, com uma altura ate 90 cm, com caules e folhas ocas e inflorescencias grandes e arredondadas, cuja cor varia entre o branco e o purpura. Existem numerosas variedades de cebolas, o que muitas vezes se evidencia na cor da casca exterior, podendo esta apresentar tons brancos, amarelados, castanhos-claros ou avermelhados.'),
habitat('A cebola e cultivada um pouco por todo o mundo. Necessita de sol e de um solo pouco pesado.'),
propriedades('a cebola pode orgulhar-se da sua longa lista de efeitos medicinais. E considerada diuretica, actua como anti-inflamatorio, e aperiente, estimula a digestao, baixa a pressao arterial, apoia a circulacao do sangue e utiliza-se como antibiotico, analgesico e remedio anti-reumatico. Dependendo da especie, pode ser colhida entre Julho e Setembro. E apanhada quando as folhas estao murchas. Pode ser preparada fresca ou atada aos molhos, pendurada num sitio seco ou guardada no frigorifico durante longos periodos.'),
cozinha('Utiliza-se a cebola para dar um sabor especial a todo o tipo de pratos de carne e ainda a comi das a base de ovos, saladas e sopas, como, por exemplo, a sopa de legumes e a sopa goulasch. Tambem se pode preparar uma pasta a base de cebolas e de condimentos, que deve ser fresca. Pode-se-lhe acrescentar um pouco de sumo de limao, porque a cebola crua ganha um sabor amargo quando esta muito tempo em contacto com o ar.'),
saude('Cebolas cruas sao indicadaspara o tratamento de inflamacoes dos sistemas respiratorio e urinario, e, tambem, para casos de infeccoes intestinais. Ajudam a manter o nivel do colesterol baixo, estimulam o apetite e a digestao, e previnem infeccoes na boca. Uma cataplasma de cebolas limpa o pus das feridas. Esfregar a pele com sumo de cebola e um remedio caseiro eficaz no tratamento de picadas de insectos. Na cosmetica a base de produtos naturais, a cebola e aplicada em tinturas diluidas para remover impurezas da pele e estimular o crescimento do cabelo. Tambem c considerada um afrodisiaco. O cebolinho (allium fistulosum), parente proximo da cebola, acua como erva sudorifera e carminativa, e ajuda a secar furunculos e abcessos.')).

record(nome('ALLIUM SATIVUM'),
nomescomum('Alho'),
sinonimo('None'),
familia('Aliaceas (Alliaceae).'),
origem('Asia Central.'),
historia('O alho e considerado uma das mais antigas plantas medicinais. Tera tido um papel importante na alimentacao em algumas culturas; o historiador grego Herodoto refere que o alho era dado aos trabalhadores da construcao da piramide de Queops, para os ajudar a recuperar as forcas. Antes da invencao do antibiotico, usava-se o alho para tratar as mais variadas infeccoes  da tuberculose ao tifo. Durante a Primeira Guerra Mundial ainda servia frequentemente para tratar feridas.'),
floracao('De Junho a Agosto.'),
caracteristica('Planta vivaz, com altura ate 1 metro e flores brancas ou rosa-claras. As folhas, rolicas na base, ocas e achatadas na parte superior, crescem a partir de um bolbo que, no fim do periodo de crescimento, desenvolve outros pequenos bolbos, aos quais chamamos “dentes de alho”.'),
habitat('A planta e provavelmente originaria de regioes aridas da Asia Central e e, hoje em dia, cultivada um pouco por todo mundo. Plantada no jardim, requer um sitio protegido e soalheiro, bem como um solo permeavel.'),
propriedades('Atribui-se ao alho um efeito anti-septico, expectorante, sudorifero, anti-hipertensor e anticoagulante. Ajuda a baixar os niveis de acucar no sangue. E rico em vitaminas A, B, C, e E. O alho e colhido depois de as ramas secarem, devendo ser colocado uns dias ao sol. A seguir, e atado em molhos e pendurado num lugar arejado e a sombra. O alho pode tambem ser conservado em oleo ou vinagre.'),
cozinha('Os dentes de alho picados conferem um sabor inconfundivel aos pratos de carne, aos molhos e as sopas, sendo imprescindiveis no preparado de manteiga de ervas. Nas saladas, basta esfregar o interior da saladeira com alho.'),
saude('o alho e um remedio caseiro antigo e conhecem-se os seus numerosos efeitos beneficos, por exemplo, em casos de infeccoes das vias respiratorias, problemas de circulacao do sangue, niveis de colesterol alto e hipertensao arterial. O alho ajuda tambem a melhorar a digestao e limpa os intestinos. Ingerido regularmente, podera prevenir alteracoes dos vasos sanguineos, resultantes do avanco da idade. Quem evita ingerir alho por causa do halito podera comer, depois de uma refeicao, salsa fresca em abundancia, pois esta ajudara a disfarcar o cheiro.')).

record(nome('ALLIUM SCHOENOPRASUM'),
nomescomum('Cebolinho, Ceboleta-de-franca'),
sinonimo('None'),
familia('Aliaceas (Alliaceae).'),
origem('Europa e Asia.'),
historia('None'),
floracao('De junho a Julho.'),
caracteristica('E uma planta que pode atingir os 30 cm de altura, apresentando folhas rolicas e aromaticas com capitulos roxos. Existem varias especies que se distinguem sobretudo atraves da espessura das folhas.'),
habitat('ja ha muito tempo que o cebolinho e uma planta domestica. Nos jardins, necessita de um lugar com sol e meia-sombra e de um solo rico em nutrientes (de preferencia calcario). O cebolinho tambem cresce em casa, em vasos a janela, onde pode ser colhido durante todo o ano. Nos campos, e possivel encontrar cebolinho bravio.'),
propriedades('o cebolinho, tal como a cebola e o alho, e rico em vitamina C e em minerais, contribuindo, desta forma, para o bom funcionamento do nosso organismo. As folhas longas e tubulosas encontram-se em crescimento constante e devem ser cortadas rente ao solo, entre Abril e Outubro. Podem ser utilizadas frescas ou congeladas. Nao e aconselhavel seca-las, pois perdem nao so a cor como tambem grande parte do seu aroma.'),
cozinha('O cebolinho e muito apreciado em saladas, pratos de legumes, ovos, carne e peixe, caldeiradas, ovos mexidos, molhos com natas e queijo quark. Picado, serve para barrar pao e e utilizado como elemento decorativo em sopas.'),
saude('o cebolinho serve sobretudo para estimular o apetite e a digestao.')).

record(nome('ALLIUM TUBEROSUM'),
nomescomum('Cebolinho chines'),
sinonimo('None'),
familia('Aliaceas (Alliaceae).'),
origem('India, Japao, Nepal e China.'),
historia('None'),
floracao('De Agosto a Setembro.'),
caracteristica('E uma planta perene que pode atingir os 40 cm. Possui folhas planas que, contrariamente as do cebolinho, nao sao ocas. A inilorescencia consiste numa umbela de flores brancas em forma de estrela, que sao polinizadas por abelhas e zangaos. Toda a planta exala um ligeiro aroma a alho.'),
habitat('Esta planta perene pode cultivar-se quer em jardins, onde necessita de sol quer em sitios com meia-sombra, com um solo piermeavel e rico em nutrientes, ou ainda em vasos a janela.'),
propriedades('O cebolinho chines possui propriedades semelhantes as da sua parente proxima, a cebola, e as do alho. Deve ser consumido sempre fresco.'),
cozinha('As folhas do cebolinho chines possuem um aroma parecido com o da cebola e com o do alho, mas menos intenso. Picadas e frescas, sao empregadas em molhos, saladas, pratos frios e de peixe, e, ainda, em pratos de ovos e de batatas. Acrescentando cebolinho chines picado a queijo quark ou a outro tipo de queijo, obtem-se um saboroso creme para barrar o pao. Juntando folhas secas de cebolinho chines, manjerico, manjerona e salsa, consegue-se uma mistura picante de ervas. O cebolinho chines e um condimento muito utilizado na culinaria asiatica.'),
saude('O cebolinho chines e famoso por estimular o apetite e a digestao.')).

record(nome('ALLIUM URSINUM'),
nomescomum('Alho-de-urso'),
sinonimo('None'),
familia('Aliaceas (Alliaceae).'),
origem('Europa.'),
historia('O valor que os nossos antepassados atribuiam a esta planta e evidente neste velho ditado alemao: “Come alho-porro na Primavera e alho-de-urso em Maio e nao veras o medico durante todo o ano.”'),
floracao('De Abril a Junho.'),
caracteristica('o alho-de-urso e uma planta perene que emana um cheiro intenso a alho, podendo atingir os 50 cm de altura. O caule e triangular e dele brotam folhas basilares lanceoladas ou ovais, com peciolos curtos, apresentando uma cor verde-escura na pagina superior e uma tonalidade mais clara na pagina inferior.'),
habitat('O alho-de-urso encontra-se preferencialmente em bosques humidos e sombrios, onde cresce de forma densa.'),
propriedades('a planta contribui para a purificacao do corpo, revelando propriedades diureticas, depurativas, anti-hipertensoras e anti-septicas. O alho de urso costuma ser utilizado fresco, mas tambem pode estar congelado ou seco. Deve colher-se antes de florir.'),
cozinha('O paladar do alho-de-urso lembra o do alho, mas nao e tao intenso nem causa o mesmo halito. As folhas picadas servem para refinar o sabor de sopas, saladas, molhos e legumes.'),
saude('Como remedio caseiro, emprega-se o alho-de-urso cm casos de dispepsia, flatulencia e colicas. Tambem estimula o apetite, fortalece o aparelho digestivo, baixa a tensao arterial e reduz os riscos de arteriosclerose.')).

record(nome('ALOE VERA'),
nomescomum('Aloe, Babosa'),
sinonimo('Aloe barbadensis.'),
familia('Liliaceas (Liliaceae).'),
origem('Africa.'),
historia('O aloe e conhecido ha muito tempo como ingrediente de locoes para a pele. Diz-se que Cleopatra, tal como muitas outras mulheres, devia em parte a sua extraordinaria beleza a esta planta.'),
floracao('De Maio a Junho.'),
caracteristica('Trata-se de uma planta perene que pode atin gir os 60 cm de comprimento, com folhas verde acinzentadas, espinhosas e suculentas, e com flores amarelas ou cor-de-laranja, dispostas em panicula.'),
habitat('Esta planta, originaria da Africa Austral e da Africa Oriental, e hoje cultivada em muitas regioes tropicais para fins comerciais. Na Europa, e conhecida por ser uma planta de vaso, pouco exigente. Muitas outras variedades de aloe servem igualmente tins medicinais, como por exemplo o Aloeferox.'),
propriedades('O aloe e cicatrizante, estimula a secrecao biliar e actua como laxante. Utilizam-se tambem os seus extractos com propriedades emolientes (tornam a pele maleavel e macia]. Para extrair o suco espesso desta planta, cortam-se as pontas das folhas. Aloes plantados em vasos podem, contudo, perder parte substanciai do seu efeito medicinal.'),
cozinha('None'),
saude('O suco viscoso do aloe e geralmente aplicado em casos de queimaduras, escoriacoes e escaldoes. Cautelosamente, esfregam-se com essa substanciaas zonas da pele afectadas, de modo a aliviar a dor e a prevenir infeccoes. Na industria cosmetica, o aloe aplica-se em cremes para maos e rosto, assim como em champos e em protectores solares.')).

record(nome('ALTHAEA OFFICINALIS'),
nomescomum('Alteia'),
sinonimo('None'),
familia('Malvaceas (Malvaceae).'),
origem('Europa, Asia e Africa do Norte.'),
historia('Ja na antiguidade, o filosofo grego Teofrasto relatava a eficacia da mistura de alteia e vinho como remedio para a tosse.'),
floracao('De Junho a Setembro.'),
caracteristica('E uma planta perene que pode atingir 1,5 m de altura. Possui uma raiz branca e forte, assim como caules erectos e pilosos. As folhas trilobadas tem peciolos curtos e uma base cordiforme. As flores, de cor  branca ou rosa-claro, encontram-se dispostas em cachos terminais ou axilares.'),
habitat('A alteia tem preferencia por solos salinos e humidos, como, por exemplo, os que se situam perto da costa litoral. Ai, cresce de forma bravia. E cultivada em grande quantidade, para fins medicinais. No jardim, necessita de sol e de terra humida e compacta.'),
propriedades('A alteia possui propriedades anti-inflamatorias, expectorantes e laxantes. As folhas podem ser colhidas entre Maio e Agosto, as flores assim que comecam a abrir, enquanto as raizes de Outubro ate a Primavera seguinte. Todas as partes podem ser lentamente secas a sombra.'),
cozinha('As raizes frescas de plantas bienais podem ser preparadas como se fossem batatas e as folhas jovens como se fossem legumes. Quanto as sementes, podem ser adicionadas a saladas.'),
saude('A raiz e considerada um bom remedio para a tosse, sobretudo quando se trata de criancas. Tambem e utilizada para produzir elixires e pomadas ou para tratar furunculos e abcessos. Uma infusao de alteia acelera a cura da pele quando esta irritada por um escaldao.')).

record(nome('ANETHUM GRAVEOLENS'),
nomescomum('Endro, Aneto'),
sinonimo('None'),
familia('Apiaceas (Apiaceae).'),
origem('A origem e desconhecida, uma das ervas mais antiga'),
historia('O endro ja era utilizado no antigo Egipto. Uma receita medicinal relatada no papiro Ebers [cerca de 1600 a. C.) recomenda o endro como analgesico. Na Grecia antiga, colocava-se a planta nos olhos para ajudar a adormecer. Na Idade Media, julgava-se que queimar endro afastava as nuvens da trovoada. O termo alemao para endro e "dill", deriva do arcaico "dylla", que significa aliviar, acalmar.'),
floracao('De Julho a Setembro.'),
caracteristica('Planta herbacea, anual, com caule erecto e fistuloso. Pode atingir os 75 cm de altura. As folhas possuem peciolos que alargam na base, formando uma bainha, envolvendo o caule. As folhas sao, portanto, invaginantes. As numerosas flores amarelas encontram-se ordenadas em umbelas, que podem atingir 15 cm de largura. A planta exala um cheiro aromatico muito tipico, enquanto os frutos leves revelam um sabor picante.'),
habitat('Esta antiga planta de cultivo precisa de sol e de meia-sombra, exigindo um solo pouco seco e permeavel. Na Europa Central, pode-sc encontrar endro bravio a beira dos caminhos, na orla de terras araveis e em areas de pousio.'),
propriedades('o endro estimula a digestao, e carminativo, diuretico e aromatico. Para a sua preparacao, utilizam-se as pontas dos rebentos e as sementes. A planta pode ser colhida ate ao Outono e utilizada fresca ou congelada. Tambem pode ser seca mas, nesse caso, corre-se o risco de se perder parte do aroma. As sementes sao colhidas quando a cor das umbelas muda para castanho.'),
cozinha('As folhas do endro servem para refinar o sabor de sopas, de molhos e de todo o tipo de pratos de peixe ou de carne (como, por exemplo, peixe cozido ou carne de borrego). Tambem conferem um sabor requintado a pratos frios, pratos de ovos ou queijo quark, a saladas de tomate ou de pepino e a confeccao de manteiga de ervas. As umbelas e as sementes sao um opimo tempero para preparar pepinos em conserva. As sementes maduras moidas sao igualmente um excelente condimento, podendo ser empregadas como alternativa aos cominhos. O oleo e o vinagre ficam com um sabor requintado quando se misturam com endro.'),
saude('o endro e uma erva medicinal muito apreciada. E considerado um remedio para a tosse, a gripe e as constipacoes. E carminativo e alivia colicas intestinais. Mastigar as sementes disfarca o mau halito. O endro podera tambem aumentar o leite materno e evitar colicas nos bebes, quando tomado regularmente durante a gravidez. Para uso externo, e indicado em casos de ulceras e inflamacoes nos olhos. Mergulhar as maos e os pes numa infusao de endro fortalece as unhas.')).

record(nome('ANGELICA ARCHANGELICA'),
nomescomum('Angelica, Erva-piolheira'),
sinonimo('None'),
familia('Apiaceas (Apiaceae).'),
origem('A disseminacao desta planta abrange a Europa Centr'),
historia(''),
floracao('De Junho a Agosto'),
caracteristica('Planta bienal e aromatica com caule vermelho, fistuloso e sulcado. Pode atingir os 2 m de altura. Possui folhas grandes, pinuladas e bi ou trifoliadas, de cor verde-clara. As flores brancas-esverdeadas estao dispostas em umbelas. A planta possui um cheiro intenso e aromatico e um sabor picante e amargo.'),
habitat('Em jardins, gosta preferencialmente de um sitio ao sol ou com meia-sombra e de um solo que nao seja demasiado seco. Na Europa Central, cresce bravia e gosta de terra humida, como, por exemplo, a que se encontra perto de rios e ribeiros, desfiladeiros e bosques pouco secos.'),
propriedades('Actua como anti-septico, estimula o apetite e adigestao e e antiespasmodica. Os caules e as folhas sao colhidos no inicio do Verao, enquanto as sementes se apanham depois de amadurecerem, tambem no Verao, e as raizes no fim do Outono do segundo ano (ja com as folhas murchas). As raizes e as sementes podem tambem ser conservadas secas.'),
cozinha('Caules e folhas frescas podem ser aproveitados como condimento para sopas, molhos e saladas. As raizes servem para a producao de chas, licores e aguardente de ervas.'),
saude('A angelica e indicada como tonico e e empregada no alivio de indisposicoes estomacais, gases e colicas, bem como na melhoria da circulacao do sangue.')).

record(nome('ANTHRISCUS CEREFOLIUM'),
nomescomum('Cerefolio, Salsa-de-burro'),
sinonimo('Anthriscus trichospermus.'),
familia('Apiaceas (Apiaceae).'),
origem('Europa do Sul Asia e Africa do Norte.'),
historia('Foram encontrados pequenos recipientes com cerefolio no tumulo de Tutankhamon, o que revela o quao apreciada era esta planta no antigo Egipto. Provavelmente, foram os romanos que a trouxeram para a Europa Central.'),
floracao('De Maio a Agosto.'),
caracteristica('Trata se de uma planta anual que pode atingir os 60 cm de altura. Possui um caule fistuloso e canelado, bem como folhas pinuladas verde-claras. As tlores, pequenas e brancas, estao dispostas em umbelas. Destaca-se o sabor tipico e intenso a anis.'),
habitat('Pode-se encontrar o cerefolio a beira de caminhos e em terrenos baldios. Plantado em jardins, necessita de sol ou de meia-sombra, bem como de um solo com boa drenagem, ligeiramente humido.'),
propriedades('o cerefolio estimula a digestao e actua como diuretico e depurativo. Pode ser colhido entre meados de Maio e finais de Novembro. Nao e proprio para ser guardado.'),
cozinha('As folhas frescas e aromaticas podem ser utilizadas como tempero em molhos (como, por exemplo, o “molho verde de Frankfurt”), em sopas e em diversos pratos, inclusive pratos de carne de bor rego, de peixe, de queijo "quark" e de ovos. Servem tambem para preparar vinagre e uma saborosa sopa de cerefolio.'),
saude('A erva actua de forma benefica sobre o aparelho digestivo e ajuda a diminuir a tensao arterial. O suco de cerefolio fresco e benefico em casos de problemas cutaneos, nomeadamente eczemas e abcessos, mas tambem em feridas. Uma infusao feita a partir das flores pode ser utilizada na cosmetica, em mascaras faciais e na limpeza da pele.')).

record(nome('APIUM GRAVEOLENS'),
nomescomum('Aipo, Rabaca'),
sinonimo('None'),
familia('Apiaceas (Apiaceae).'),
origem('Europa, Asia e Africa do Norte.'),
historia('Ha registos que relatam o cultivo do aipo ha 3000 anos no Egipto e, desde o seculo v a. C., tambem na China. Na antiga Grecia e na antiga Roma, o aipo deve ter desempenhado um papel nos rituais funebres, pois aparece em inumeros tumulos. Chegou a Europa Central provavelmente apenas na Idade Media.'),
floracao('De Julho a Setembro.'),
caracteristica('Planta bienal, desenvolve poucas folhas no primeiro ano, podendo chegar a atingir 1 metro de altura no segundo. Possui um caule fistuloso, folhas com peciolos longos, pinuladas e com margem dentada, assim como flores pequenas brancas em umbelas, que se desenvolvem apenas no segundo ano. E de destacar o forte aroma que emana de toda a planta.'),
habitat('o aipo, uma planta de cultivo milenar, cresce naturalmente em solos salinos. No jardim, requer terra humida e rica em nutrientes.'),
propriedades('o aipo actua como remedio anti-reumatico, diuretico e anti-hipeitensor, sendo ainda antiespasmodico e carminativo. E tambem considerado um bom anti-septico, no que diz respeito a problemas das vias urinarias e da zona genital. Os tuberculos e os peciolos engrossados sao cortados entre Outubro e Novembro, antes das primeiras geadas. Os tuberculos conservam-se bem, durante algum tempo, num lugar fresco. Para uso medicinal, podem ser secos e guardados num recipiente hermeticamente fechado. Pode-se embrulhar em papel de jornal o aipo que nao foi consumido apos a colheita, guardando-o num lugar fresco. Tambem e possivel congela-lo para ser cozido. As folhas devem ser cortadas e consumidas na altura, mas se houver sobras podem ser congeladas ou secas.'),
cozinha('Existem algumas variedades de aipo, entre as quais se destaca o aipo pequeno (A.graveolens var. secalinum), que tem nonnalmente raiz fina e folhas particularmente aromaticas. Estas sao utilizadas em sopas e, quando secas, servem para fazer sal de aipo. O aipo-rabano (A. graveolens var. rapaceum) possui uma raiz carnuda, que pode ser usada crua, em saladas. O aipo-de-talo (A. graveolens var. dulce) dispoe de peciolos espessos, que podem ser preparados como legumes e acompanhar pratos frios e entradas servidas com cerveja.'),
saude('O aipo e considerado um diuretico. As suas sementes eram utilizadas antigamente para tratar problemas de bexiga, problemas renais e tambem no alivio do reumatismo e da artrite. A planta, a qual ja desde a antiguidade e atribuido um efeito afrodisiaco, ja nao e tao frequentemente usada para fms medicinais. Visto ser rica em vitaminas e sais minerais, serve sempre para completar a alimentacao.')).

record(nome('ARMORACIA RUSTICANA'),
nomescomum('Rabano-rustico'),
sinonimo('None'),
familia('Brassicaceas (Brassicaceae).'),
origem('Europa do Sul e Oriental.'),
historia('None'),
floracao('De Maio a Julho.'),
caracteristica('E uma planta perene com raiz aprumada, carnuda e longa, que sustenta um caule esquinado e sulcado. Pode atingir 1 metro de altura. As folhas basilares sao grandes, longas e ovais, com margem crenada, enquanto as folhas caulinares sao pinuladas. As pequenas flores brancas encontram-se dispostas em cachos'),
habitat('O rabano-rustico cresce de forma bravia em prados e a beira de caminhos. No jardim, e frequentemente cultivado como planta anual. E uma planta que requer sol e meia-scmibra e terra humida, rica em nutrientes.'),
propriedades('O rabano e conhecido por aumentar a transpiracao, estimular a digestao e possuir efeitos anti-reumaticos e diureticos. A raiz e colhida no Outono e pode ser conservada temporariamente num lugar escuro e humido, coberta de areia.'),
cozinha('o rabano-rustico serve para temperar molhos e para acompanhar pratos de carne e de peixe. E tambem um bom ingrediente para preparados de maionese ou de mostarda.'),
saude('A planta possui qualidades terapeuticas, destacando-se os seus efeitos diuretico, digestivo e sudorifero, que a tornam indicada para casos de febre, constipacoes e gripe. A raiz e vulgamente usada como remedio caseiro contra a rinite alergica, podendo  ser picada fresca e ingerida com pao. A raiz moida pode ser utilizada em compressas para aliviar frieiras (nao abertas).')).

record(nome('ARNICA MONTANA'),
nomescomum('Arnica, Craveiro-dos-alpes'),
sinonimo('None'),
familia('Asteraceas (Asteraceae)'),
origem('Europa'),
historia('None'),
floracao('De Junho a Julho.'),
caracteristica('Trata se de uma planta perene, aromatica, que pode atingir 60 cm de altura. Possui um rizoma casta nho, um caule piloso e uma roseta-basilar, composta por folhas lanceoladas ovoides. A inflorescencia e constituida por pequenas bracteas interflorais amarelas e grandes bracteas involucrais laranja-amareladas.'),
habitat('Na Europa Central,  a arnica cresce em prados e bosques, situados nas montanhas. Chamamos a atencao para o facto de se tratar de uma planta protegida em paises como a Alemaha, a Austria e a Suica, razao pela qual nao pode ser colhida. Cultivada no jardim, necessita de sol e de um solo sem calcario.'),
propriedades('A arnica caracteriza-se por ser uma erva anti-septica e anti-reumatica que previne a artrite. As flores sao colhidas entre Junho e Agosto e o rizoma no Outono, apos as folhas murcharem.'),
cozinha('None'),
saude('A arnica era antigamente uma planta medicinal muito conhecida. Consideravam-na um estimulante da circulacao sanguinea e um excelente remedio para a angina de peito, "angina pectoris" (o poeta alemao Goethe bebia cha de arnica em idade avancada, para aliviar a sua angina de peito). Sabemos hoje que a arnica contem substancias toxicas em quantidades consideraveis, razao pela qual o seu uso e actualmente apenas externo. O efeito anti-septico da pomada de arnica mostra-se eficaz no tratamento de contusoes,  entorses e dores musculares, melhorando a irrigacao sanguinea nas partes lesionadas e acelerando a cura.')).

record(nome('ARTEMISIA ABROTANUM'),
nomescomum('Abrotano'),
sinonimo('None'),
familia('Asteraceas (Asteraceae).'),
origem('Asia Menor e possivelmente tambem na Europa do Sul'),
historia('O nome cientifico desta planta provem da rainha persa Artemisia, que, segundo consta, ter-se-a interessado por botanica. O abrotano chega a Europa Central por volta do sec. IX ou X, onde e cultivado nos jardins dos mosteiros. Na epoca da caca as bruxas, acusavam-nas de usar o abrotano para fabricar pocoes magicas.'),
floracao('De julho a Outubro.'),
caracteristica('Trata-se de uma planta perene, que pode atingir 1 metro de altura e apresenta folhas verde-acinzentadas, pinuladas e lanceoladas, bem como flores pequenas, amareladas e dispostas em inflorescencias paniculadas. A planta caracteriza-se pelo cheiro a limao das folhas.'),
habitat('Em cultivo, a planta requer um lugar com sol ou meia-sombra e um solo permeavel, preferencialmente rico em calcario.'),
propriedades('A planta e conhecida por ser tonificante e tambem repelente de insectos. Os rebentos frescos podem ser colhidos entre a Primavera e o Outono e utilizados frescos ou secos.'),
cozinha('O abrotano pode ser empregado em pequenas quantidades como condimento. Neste caso, utilizam-se as pontas das folhas frescas ou secas para refinar o sabor de molhos ou temperar pratos gordos, como, por exemplo, pato assado.'),
saude('A planta tem propriedades digestivas. Colocada num roupeiro, repele as tracas, e, plantada no jardim, pode afastar a borboleta branca da couve.')).

record(nome('ARTEMISIA ABSINTHIUM'),
nomescomum('Absinto, Santonica, Amargoso, Erva-das-sezoes'),
sinonimo('None'),
familia('Asteraceas (Asteraceae)'),
origem('Europa e Asia.'),
historia('Antigamente, esta planta era utilizada na producao de absinto, uma bebida toxica e viciante, muito popular na Franca do sec. XIX. Depois de se registrarem varios casos de graves complicacoes de saude devido ao consumo do absinto, este foi finalmente proibido.'),
floracao('De julho a Setembro.'),
caracteristica('Planta perene, que pode atingir 1,2 m de altura, com caules verde acinzentados, folhas pinuladas densa mente pilosas e flores pequenas e amarelas, dispostas em panicula. Caracteriza-se pelo cheiro aromatico forte e pelo sabor muito amargo.'),
habitat('Na Europa Central, o absinto bravio cresce em lugares secos, a beira de caminhos e em terrenos em pousio. O absinto cultivado no jardim precisa de sol ou de meia-sombra e de terra permeavel.'),
propriedades('O absinto caracteriza-se por ser aromatico, amargo, digestivo e estimulante. De Maio a Outubro, podem colher-se os rebentos. Para secar a planta, deve-se colhe-la antes da floracao.'),
cozinha('O absinto e muito apreciado como aroma de bebidas alcoolicas. Em pequenas quantidades, pode ser utilizado para refinar o sabor de pratos de carne ou de caldeiradas. Tambem pode ser util como repelente.'),
saude('O absinto amargo - em latim, absinthium significa desagradavel - actua beneficamente sobre o aparelho digestivo, nomeadamente, o estomago e a vesicula biliar.')).

record(nome('ARTEMISIA DRACUNCULUS'),
nomescomum('Estragao, Erva-dragao'),
sinonimo('None'),
familia('Asteraceas (Asteraceae).'),
origem('Sul da Russia e Asia Central.'),
historia('O estragao e mencionado, pela primeira vez, em documentos chineses datados de 3000 a. C. Da China foi levado para o mundo arabe e, na epoca das cruzadas, tambem chegou a Europa.'),
floracao('De julho a Outubro.'),
caracteristica('Trata-se de uma planta perene, que pode alancar  1 metro de altura, com folhas lanceoladas e sesseis ou com peciolos curtos, e com pequenos capitulos discretos, de cor branca esverdeada. Exala um cheiro tipicamente aromatico.'),
habitat('O estragao e cultivado um pouco por todo o mundo. Requer terra permeavel, humida e rica em nutrientes. Precisa de um lugar quente e abrigado do vento e necessita de proteccao no Inverno.'),
propriedades('O estragao e conhecido como uma eiva aromatica I	e digestiva. As folhas destinadas a ser guardadas podem ser colhidas entre Maio e Junho. Os rebentos em flor colhem-se entre Julho e Agosto. Para secar esta en-a, deve-se escolher um lugar a sombra e arejado. Para a guardar, utilizam-se recipientes de vidro ou porcelana.'),
cozinha('As folhas frescas de estragao sao indicadas para refinar o sabor de sopas, molhos, queijo quark, saladas e pratos de carne de ave. Podem tambem ser utilizadas no preparo de vinagre de ervas, licor de ervas ou mostarda. Recomendam-se, entre as diversas variedades existentes, as de estragao frances ou alemao, muito apreciadas devido ao seu paladar mais aromatico.'),
saude('O estragao estimula o apetite e a digestao e pode ser tambem utili zado como calmante e soporifero. Antigamente, em casos de dores de dentes, mastigava-se a raiz.')).

record(nome('ARTEMISIA VULGARIS'),
nomescomum('Artemisia, Erva-de-fogo'),
sinonimo('None'),
familia('Asteraceas (Asteraceae).'),
origem('Europa, Asia, Africa do Norte.'),
historia('A artemisia tera sido utilizada pelos romanos para forrar as suas sandalias, de modo a manterem os pes saudaveis.'),
floracao('De Agosto a Novembro.'),
caracteristica('Trata se  de uma planta aromatica e perene, podendo atingir 1,5 m de altura. Apresenta folhas pinuladas, verde-escuras e alter nas, cujo lado inferior e lanoso e de cor branca. Os capitulos, dispostos em panicula, sao pequenos e apresentam uma cor que varia entre o averme¬ lhado e o amarelo.'),
habitat('A artemisia esta espalhada por vastas areas da Europa e cresce preferencialmente em terrenos baldios, a beira dos caminhos e junto a arbustos. Cultivada, revela-se pouco exigente na manutencao, apenas necessitando de sol.'),
propriedades('A artemisia e uma erva amarga, sedativa e aromatica, que estimula o apetite e a digestao. As folhas e os rebentos podem ser colhidos ate a planta florir. Paniculas destinadas a serem secas cortam-se pouco antes da florescencia, no final do Verao.'),
cozinha('Folhas frescas ou secas sao ideais para pratos gordos, como, por exemplo, pratos de carne de porco, borrego ou pato e saladas.'),
saude('A artemisia e aperiente, digestiva e e mais suave do que as suas parentes, pelo que podera ser ingerida em forma de cha durante longos periodos.')).

record(nome('BARBAREA VULGARIS'),
nomescomum('Erva-de-Santa-Barbara, Erva-dos-carpinteiros'),
sinonimo('None'),
familia('Brassicaceas (Brassicaceae).'),
origem('Europa, Asia e Africa do Noite.'),
historia('A planta deve o seu nome ao facto de ficar verde e comestivel a partir do dia 4 de Dezembro, dia de Santa Barbara.'),
floracao('De Abril a Julho.'),
caracteristica('Trata-se de uma planta bienal, que pode atingir os 90 cm de altura. Possui um caule ramificado, com folhas basilares ovadas e folhas caulinares pinuladas. As infiorescencias sao compostas por tlores de cor amarelo-vivo.'),
habitat('Pode-se encontrar a planta em prados, a beira de caminhos ou nas orlas de terras cultivadas, bem como nas margens de rios e ribeiros. No jardim, requer um sitio pouco seco com meia-sombra. Tambem pode ser cultivada numa estufa fria.'),
propriedades('Caracteriza-se por estimular o metabolismo e purifiar o organismo. E rica em vitaminas e sais minerais. Trata-se de uma erva que tambem esta disponivel no Inverno.'),
cozinha('As folhas em roseta basilar, apanhadas entre Dezembro e Maio, podem ser preparadas e cozinhadas como os espinafres. As folhas caulinares sao colhidas na Primavera e servem para saladas (a mistura com folhas de outras plantas disfarca o sabor um pouco forte). Tambem e ideal para dar um toque especial ao queijo e ao queijo quark, a manteiga de ervas e a sopas leves.'),
saude('Dado ser rica em vitamina C, era, em tempos, ingerida para combater o escorbuto. Hoje em dia, e apreciada pelo seu efeito diuretico, cicatrizante, estimulante do apetite e purificador do sangue.')).

record(nome('BORAGO OFFICINALIS'),
nomescomum('Borragem, Borago'),
sinonimo('None'),
familia('Boroginaceas (Boroginaceae).'),
origem('E, provavelmente, oriunda do Mediterraneo.'),
historia('Antigamente, pensava-se que afastava a tristeza, por isso, o sabio romano Plinio afirmava que a borragem «traz sempre alegria».  Tambem nos livros	medievais sobre ervas, esta planta era apresentada como remedio para a melancolia.'),
floracao('De Maio a Agosto.'),
caracteristica('Planta	anual,  que pode atingir os 60 cm de altura, com um caule ramificado e hispido.  As folhas basilares sao grandes, ovais, inteiras ou dentadas; as folhas caulinares sao lanceoladas e pilosas. As flores azuis e vistosas formam unia panicula ligeiramente ramificada.'),
habitat('Na Europa Central, apenas cresce de forma selvagem em campos, prados e terrenos baldios. Cultivada no jardim, requer sol e terra permeavel, rica em nutrientes, de preferencia calcario.'),
propriedades('A planta possui propriedades diureticas, anti-reumaticas, anti-inilamatorias, sudoriferas e expectorantes.'),
cozinha('Na culinaria, utilizam-se geralmente os rebentos, as folhas e as flores, que sao colhidos entre Maio e Outubro e preparados ainda frescos, podendo tambem ser congelados. As folhas sao usadas na confeccao de salada de pepino ou outras, assim como na preparacao do «molho verde de Frankfurt».'),
saude('A planta e rica em mucilagem, aliviando problemas relacionados com as vias respiratorias. As flores tem propriedades diureticas e sudoriferas. O oleo extraido da semente da planta e rico em acidos gordos poliinsaturados, usados no tratamento de eczemas e de outras doencas cutaneas cronicas.')).

